#!/bin/bash
set -e

display_help() {
    echo "Usage: $(basename "$0") [-h] [-q queue] N_WORKERS ENV_NAME" 
    echo "  The utility that launch a Dask cluster through PBS."
    echo "  The answer to the ultimate question of life, the universe and everything."
    echo
    echo "  Options:"
    echo "    -h    display this help and exit"
    echo "    -q    queue"
    echo
}

##
# ARGUMENTS
##
queue="gpu"
nthreads=4
nprocs=4
while getopts ':hq:t:p:' option; do
    case "${option}" in
        q)  # select a non-default queue
            queue="$OPTARG"
            ;;
        t)  # number of threads per process
            nthreads=$OPTARG
            ;;
        p)  # number of processes per worker
            nprocs=$OPTARG
            ;;

        # by having ":...", we want to handle errors ourselves
        :)  # missing argument
            printf "missing argument for -%s\n" "$OPTARG" >&2
            display_help
            exit 1
            ;;
        \?) # illegal option
            printf "illegal option: -%s\n" "$OPTARG" >&2
            display_help
            exit 1
            ;;

        # help or blank
        h | *)  
            display_help
            exit 0
            ;;
    esac
done
shift $((OPTIND - 1))

if [ "$#" -ne 2 ]; then
    echo "missing positional arguments"
    display_help
    exit 1
fi

conda_base=$(conda info --base)

##
# SCHEDULER
##
n_workers=${1}
echo "Launching Dask scheduler"
s=$(qsub -v conda_base=${conda_base} -q core12 launch-dask-scheduler.sh) # launch on a cpu node
sjob=${s%.*}
echo ${s}

# block until the scheduler job starts
while true; do
    status=$(qstat ${sjob} | tail -n 1)
    echo "... ${status}"
    if [[ ${status} =~ " R " ]]; then
        break
    fi
    sleep 1
done


##
# WORKER
##

# define core count
ppn=${nprocs}
if [[ ${queue} == gpu* ]]; then
    echo "A GPU can only bound to 1 process, override ppn=1"
    ppn=1
fi

env_name=${2}
echo "Launching Dask workers (${n_workers}) with \"${env_name}\""

for i in $(seq 1 ${n_workers}); do
    qsub \
        -N "dask-worker-${i}" \
        -v conda_base=${conda_base},nprocs=${nprocs},nthreads=${nthreads},env_name=${env_name} \
        -q "${queue}" \
        -l nodes=1:ppn=${ppn}
        launch-dask-worker.sh
done